project:
  type: website
  output-dir: docs

website:
  title: "Bryan Whiting"
  site-url: https://www.bryanwhiting.com
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/bryan-whiting/"
      - icon: github
        href: https://github.com/bryanwhiting
      - icon: twitter
        href: "https://twitter.com/bryanwhiting"
format:
  html:
    theme: cosmo
    css: styles.css



