project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: true

website:
  title: "Bryan Whiting"
  site-url: https://www.bryanwhiting.com
  google-analytics: "UA-85616639-1"
  reader-mode: false # https://quarto.org/docs/websites/website-navigation.html#reader-mode
  page-footer: 
    left: "Copyright 2021-2024, Bryan Whiting" 
    right: 
      - icon: github
        href: https://github.com/bryanwhiting
      - icon: linkedin
        href: "https://www.linkedin.com/in/bryan-whiting/"
      - icon: twitter
        href: "https://twitter.com/bryanwhiting"
      - icon: rss
        href: index.xml
  search: true
  body-footer: | 
    _________________________ <br> _For coaching on data analytics or machine learning, <a href="mailto:bryanwhitingcoaching@gmail.com">reach out</a>_.
  sidebar:
    style: "docked"
    background: light
    subtitle: Data scientist | tech | father
    tools:
      - icon: github
        menu:
          - text: This blog
            url:  https://github.com/bryanwhiting/blog
          - text: Profile
            url: https://github.com/bryanwhiting
      - icon: linkedin
        href: "https://www.linkedin.com/in/bryan-whiting/"
      - icon: twitter
        href: "https://twitter.com/bryanwhiting"
      - icon: rss
        href: index.xml
    contents:
      - index.qmd
      - books.qmd
      - lists.qmd
      - christianity.qmd
      - about.qmd
      

format:
  # https://quarto.org/docs/reference/formats/html.html
  html:
    # author: "Bryan Whiting"
    theme: sandstone
    css: styles.css
    comments:
      giscus: 
        repo: bryanwhiting/blog
    # comments:
      # hypothesis: true
      # utterances:
      #   repo: jthomasmock/themockup-blog
    toc: true
    appendix-style: none
    toc-location: "left"
    smooth-scroll: true
    code-copy: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    # mainfont: "Lato"
    # monofont: "Fira Mono"
    footnotes-hover: true
    citations-hover: true
    # fontsize: 1em



