project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: true

website:
  title: "Bryan Whiting"
  site-url: https://www.bryanwhiting.com
  google-analytics: "UA-85616639-1"
  twitter-card: 
    creator: "@bryanwhiting"
    card-style: summary_large_image
  open-graph: true
  reader-mode: false # https://quarto.org/docs/websites/website-navigation.html#reader-mode
  page-footer: 
    left: "Copyright 2021-2024, Bryan Whiting" 
    right: 
      - icon: github
        href: https://github.com/bryanwhiting
      - icon: linkedin
        href: "https://www.linkedin.com/in/bryan-whiting/"
      - icon: twitter
        href: "https://twitter.com/bryanwhiting"
      - icon: rss
        href: index.xml
  search: true
  body-footer: |
    _________________________ <br> <br> <i><a href="https://www.bryanwhiting.com/about">Bryan</a> lives somewhere at the intersection of faith, fatherhood, and futurism and writes about <a href="https://www.bryanwhiting.com/tech">tech</a>, <a href="https://www.bryanwhiting.com/books">books</a>, <a href="https://www.bryanwhiting.com/christianity">Christianity</a>, <a href="https://www.bryanwhiting.com/gratitude">gratitude</a>, and <a href="https://www.bryanwhiting.com/">whatever's on his mind</a>. If you liked reading, perhaps you'll also like subscribing: <br><br> </i><iframe src="https://embeds.beehiiv.com/106e21ff-1989-43d2-9bd7-d4a4c4404ab6?slim=true" data-test-id="beehiiv-embed" height="52" frameborder="0" scrolling="no" style="margin: 0; border-radius: 0px !important; background-color: transparent;"></iframe>
  sidebar:
    style: "docked"
    background: light
    subtitle: Data scientist | tech | father
    tools:
      - icon: github
        menu:
          - text: This blog
            url:  https://github.com/bryanwhiting/blog
          - text: Profile
            url: https://github.com/bryanwhiting
      - icon: linkedin
        href: "https://www.linkedin.com/in/bryan-whiting/"
      - icon: twitter
        href: "https://twitter.com/bryanwhiting"
      - icon: rss
        href: index.xml
    contents:
      - index.qmd
      - tech.qmd
      - books.qmd
      - lists.qmd
      - christianity.qmd
      - gratitude.qmd
      - creative.qmd
      - about.qmd
      

format:
  # https://quarto.org/docs/reference/formats/html.html
  html:
    # author: "Bryan Whiting"
    theme: sandstone
    css: styles.css
    template-partials:
      - title-metadata.html
      # - title-block.html
    
    comments:
      giscus: 
        repo: bryanwhiting/blog
    # comments:
      # hypothesis: true
      # utterances:
      #   repo: jthomasmock/themockup-blog
    toc: true
    appendix-style: none
    toc-location: "left"
    smooth-scroll: true
    code-copy: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    # mainfont: "Lato"
    # monofont: "Fira Mono"
    footnotes-hover: true
    citations-hover: true
    # fontsize: 1em
    callout-appearance: simple
    callout-icon: false 
    title-block-banner: true
    date-format: "dddd MMMM D, YYYY"



