project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: true

website:
  title: "Bryan Whiting"
  site-url: https://www.bryanwhiting.com
  google-analytics: "UA-85616639-1"
  search: true
  body-footer: |
    _Bryan is passionate about building great products with data and empowering individuals to reach their potential. Please reach out at <a href="mailto:bryanwhitingcoaching@gmail.com">bryanwhitingcoaching@gmail.com</a> to get mentorship or coaching for your life or business._
  sidebar:
    style: "docked"
    background: light
    tools:
      - icon: linkedin
        href: "https://www.linkedin.com/in/bryan-whiting/"
      - icon: github
        href: https://github.com/bryanwhiting
      - icon: twitter
        href: "https://twitter.com/bryanwhiting"
      - icon: rss
        href: index.xml
    contents:
      - index.qmd
      - about.qmd
      

format:
  # https://quarto.org/docs/reference/formats/html.html
  html:
    # author: "Bryan Whiting"
    theme: cosmo
    css: styles.css
    # comments:
      # hypothesis: true
      # utterances:
      #   repo: jthomasmock/themockup-blog
    toc: true
    toc-location: "left"
    smooth-scroll: true
    code-copy: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    # mainfont: "Lato"
    # monofont: "Fira Mono"
    footnotes-hover: true
    citations-hover: true
    # fontsize: 1em



