on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render and deploy Blog

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace smart quotes in Markdown files
        #run: |
        #  chmod +x ./replace_smart_quotes.sh
        #  ./replace_smart_quotes.sh      
      
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.515

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.1' # The R version to download (if necessary) and use.
      
      - uses: r-lib/actions/setup-renv@v2
      # - name: Cache packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{ env.RENV_PATHS_ROOT }}
      #     key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-renv-
      # 
      # - name: Restore packages
      #   shell: Rscript {0}
      #   run: |
      #     if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
      #     renv::restore()

      - name: Render blog 
        run: |
          quarto render
      
      - name: Push rendered code
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
